import HeaderNews from "@/components/Header-News.jsx";

const TCs = () => {
    return (
        <div>
            <HeaderNews title={"CLOAK ROOM TERMS & CONDITIONS\n"} />

            <div className="max-w-4xl mx-auto p-6 text-sm md:text-base leading-relaxed items-center justify-center">
                <p className="mb-4">
                    BY CLOAKING YOUR JACKET OR ITEM IN THE BAR BAMBI CLOAK ROOM, YOU (AND ALL THOSE CLAIMING THROUGH YOU) ACCEPT THAT A CONTRACT IS FORMED BETWEEN US ON THE TERMS AND CONDITIONS (AND NO OTHER) AS SET OUT BELOW AND IN FULL VIA THE TERMS LISTED ON OUR WEBSITE <span className={"underline"}>BARBAMBI.COM.AU</span> WHICH CAN BE VIEWED ON THE BELOW QR CODE.
                </p>

                <p className="mb-4 font-semibold">
                    YOU WILL KEEP YOUR TICKET STUB TO BE PRESENTED WHEN RECLAIMING YOUR GARMENTS.
                </p>

                <p className="mb-4 font-semibold">
                    IF NO TICKET IS PRESENTED, NO GARMENTS WILL BE RETURNED.
                </p>

                <p className="mb-4">
                    BAR BAMBI WILL MAKE ALL ATTEMPTS TO ENSURE YOUR GARMENTS ARE RETURNED TO YOU IN THE CONDITION RECEIVED.
                </p>

                <p className="mb-4">
                    BAR BAMBI ACCEPTS NO RESPONSIBILITY IF GARMENTS ARE NOT IN ORIGINAL CONDITION WHEN RETURNED.
                </p>

                <p className="mb-4">
                    BAR BAMBI ACCEPTS NO RESPONSIBILITY FOR LOST OR STOLEN GARMENTS OR ITEMS.
                </p>

                <p className="mb-4">
                    UNCLAIMED GARMENTS WILL BE DONATED TO A CHARITABLE ORGANISATION IF NOT CLAIMED 14 DAYS AFTER CLOAKING.
                </p>

                <p className="mb-6">
                    ALL INTERSTATE AND INTERNATIONAL GUESTS WILL NEED TO COVER ANY POSTAGE & HANDLING FEES TO HAVE GARMENTS RETURNED.
                </p>

                <ol className="list-decimal pl-6 mb-6 space-y-4">
                    <li>
                        IF YOU DO NOT ACCEPT THESE TERMS, THE JACKET OR ITEM IN WHICH YOU PLACED MUST BE IMMEDIATELY REMOVED FROM THE CLOAK ROOM.
                    </li>
                    <li>
                        YOU MUST COMPLY WITH ALL RULES AND DIRECTIONS DISPLAYED WITHIN OUR WEBSITE AND ANY DIRECTIONS GIVEN TO YOU BY OUR STAFF.
                    </li>
                    <li>
                        WE WARRANT THAT ANY SERVICES PROVIDED BY US WILL BE RENDERED WITH DUE CARE AND SKILL. WE MAKE NO OTHER EXPRESS WARRANTIES IN RELATION TO THE SERVICES WE PROVIDE. ALL OTHER WARRANTIES, REPRESENTATIONS AND CONDITIONS RELATING TO THE SERVICES (WHETHER EXPRESS OR IMPLIED AND WHETHER ARISING IN CONTRACT, AT COMMON LAW OR UNDER STATUE) ARE TO THE MAXIMUM EXTENT PERMITTED BY LAW EXPRESSLY EXCLUDED.
                    </li>
                    <li>
                        YOU ACKNOWLEDGE THAT OUR LIABILITY UNDER ANY STATUTORY RIGHT OR ANY CONDITION OR WARRANTY IMPLIED BY THE COMPETITION AND CONSUMER ACT 2010 (CTH) (OR SIMILAR STATE LEGISLATION) WHICH CANNOT BE EXCLUDED IS TO THE EXTENT PERMITTED BY LAW LIMITED, AT OUR OPTION, TO THE RE-SUPPLY OF THE SERVICES OR THE PAYMENT OF THE COST OF HAVING THE SERVICES SUPPLIED AGAIN.
                    </li>
                    <li>
                        SUBJECT TO YOUR RIGHTS UNDER THE AUSTRALIAN CONSUMER LAW (ACL) WHICH CANNOT BE EXCLUDED, WE ARE NOT LIABLE TO YOU (OR ANY OTHER PARTY) FOR ANY LOSS, DAMAGE, INJURY, OR ANY INCIDENTAL, INDIRECT, SPECIAL, CONSEQUENTIAL OR ECONOMIC LOSS OR DAMAGE (INCLUDING LOSS OF OPPORTUNITY, EXEMPLARY OR PUNITIVE DAMAGES) WHETHER TO PERSON OR PROPERTY (INCLUDING THE JACKET OR ITEM) AND WHETHER ARISING FROM DEFAULT, NEGLIGENCE, MISCONDUCT OR OTHERWISE BY US, OUR EMPLOYEES, AGENTS AND CONTRACTORS.
                    </li>
                    <li>
                        YOU MUST PAY US ALL CLOAK FEES AND OTHER COSTS REASONABLY INCURRED BY US. IF YOU LOSE OR FAIL TO PRESENT A TICKET REQUIRED TO BE PRESENTED UPON PICKING UP YOUR JACKET OR ITEM, YOU WILL NOT HAVE YOUR JACKET OR ITEM RETURNED WITHOUT PROVIDING SUFFICIENT EVIDENCE OF YOUR OWNERSHIP OF THIS ITEM.
                    </li>
                    <li>
                        WITHOUT LIMITING THE GENERAL AND/OR PARTICULAR LIEN WE HAVE OVER THE JACKET OR ITEM LEFT IN THE CLOAK ROOM (WHICH LIENS ARE EXPRESSLY PRESERVED), WE RESERVE THE RIGHT TO RETAIN POSSESSION OF THE JACKET UNTIL ALL FEES AND OTHER COSTS INCURRED BY US IN RESPECT OF THE CLOAK HAVE BEEN PAID.
                    </li>
                    <li>
                        YOU ACKNOWLEDGE THAT BY LEAVING YOUR JACKET OR ITEM IN THE CLOAK ROOM, YOU ACCEPT THESE CONDITIONS AND ACKNOWLEDGE THAT ANY UNCLAIMED GARMENTS WITHIN 7 DAYS OF CLOAKING WILL GIVE US RIGHT TO DONATE TO CHARITY OR RIGHT OF SALE IN ACCORDANCE WITH THE PROVISIONS OF THE ACT.
                    </li>
                    <li>
                        FURTHERMORE, ANY ITEM REQUEST TO BE POSTED WILL INCUR A POSTAGE AND HANDLING FEE.
                    </li>
                </ol>

                <div className="bg-gray-100 p-4 rounded-lg text-xs">
                    <p className="font-bold mb-2 underline">PRIVACY COLLECTION STATEMENT:</p>
                    <p>
                        WE COLLECT YOUR PERSONAL INFORMATION TO PROVIDE YOU WITH CLOAK ROOM SERVICES. WE MAY USE THIS INFORMATION FOR MARKETING PURPOSES AND MAY DISCLOSE YOUR PERSONAL INFORMATION TO OUR CONTRACTORS IN CONNECTION WITH PROVIDING THE SERVICES. IF YOU DO NOT PROVIDE THE INFORMATION, WE MAY NOT OFFER YOU THE SERVICES. WE DEAL WITH YOUR PERSONAL INFORMATION IN ACCORDANCE WITH THE PRIVACY ACT 1988 (CTH) AND OUR PRIVACY POLICY WHICH MAY BE UPDATED FROM TIME TO TIME.
                    </p>
                </div>
            </div>
        </div>
    )
}
export default TCs
